#!/usr/bin/env python3
"""Regenerate a repo's GEMINI.md from its AGENTS.md (BT.chore.agents-md-is-canonical).

GEMINI.md is a GENERATED file: its shared region is AGENTS.md verbatim, followed by an
Antigravity-specific tail (the Fleet & Core Skills table naming `.agents/skills/`, and anything
after it). `agent-docs` gates that the two stay in step.

WHY THIS SCRIPT EXISTS. The split shipped with a gate and no generator: the shared region was
regenerated by hand each time it was needed. Within a day of the split landing, two repos drifted
(HQ via 75354031b, engine-rs via baa7758) — in both cases a lane edited AGENTS.md correctly and had
no tool to bring GEMINI.md along. A gate that catches drift nobody can fix just converts a silent
problem into a red one, so the generator is part of the contract, not a convenience.

WHAT IS PRESERVED. Everything from the tail marker onward is the surface-specific half and is kept
byte-for-byte — this script never authors or rewrites it. Only the shared region above it is
replaced, plus the H1 and the do-not-edit banner.

Exit 0 — regenerated, or already in sync.  Exit 1 — could not run (missing file, no tail marker).

Usage:
  python3 scripts/regenerate_gemini.py                    # this repo
  python3 scripts/regenerate_gemini.py --repo <path>      # another repo
  python3 scripts/regenerate_gemini.py --repo <path> --check   # report only, write nothing
  python3 scripts/regenerate_gemini.py --all              # every repo registered in brain.toml
"""

import argparse
import re
import sys
from pathlib import Path

TAIL_MARKER = "## Fleet & Core Skills"
BANNER_RE = re.compile(r"\n(> \*\*GENERATED FILE.*?)\n\n", re.S)
DEFAULT_BANNER = """> **GENERATED FILE — do not edit by hand.**
> Everything above the Fleet & Core Skills table is copied verbatim from `AGENTS.md`; only that
> table and anything after it is Antigravity-specific. A hand edit here is silently overwritten on
> the next sync. Edit `AGENTS.md` instead, or the tail below."""


def regenerate(repo: Path, check_only=False, quiet=False):
    agents, gemini = repo / "AGENTS.md", repo / "GEMINI.md"
    if not agents.is_file():
        print(f"  {repo}: no AGENTS.md — skipping")
        return 0
    if not gemini.is_file():
        print(f"  {repo}: no GEMINI.md — skipping (nothing to regenerate)")
        return 0

    a = agents.read_text(encoding="utf-8")
    g = gemini.read_text(encoding="utf-8")

    idx = g.find(TAIL_MARKER)
    if idx == -1:
        print(
            f"  {repo}: GEMINI.md has no '{TAIL_MARKER}' marker, so the surface-specific tail "
            f"cannot be located. REFUSING to write — regenerating without it would silently "
            f"delete that half. Fix the file by hand, or add the marker."
        )
        return 1
    tail = g[idx:].rstrip()

    m = BANNER_RE.search(g)
    banner = m.group(1) if m else DEFAULT_BANNER

    lines = a.split("\n")
    head = lines[0].replace("AGENTS.md", "GEMINI.md", 1)
    body = head + "\n\n" + banner + "\n" + "\n".join(lines[1:])
    new = body.rstrip() + "\n\n" + tail + "\n"

    if new == g:
        if not quiet:
            print(f"  {repo}: already in sync")
        return 0
    if check_only:
        print(f"  {repo}: WOULD REGENERATE (shared region differs from AGENTS.md)")
        return 0
    gemini.write_text(new, encoding="utf-8")
    print(f"  {repo}: regenerated ({len(new.splitlines())} lines, tail preserved)")
    return 0


def brain_repos(start: Path):
    """Every repo_path in brain.toml, plus the brain root and the tier dirs."""
    root = start.resolve()
    while root != root.parent and not (root / "brain.toml").is_file():
        root = root.parent
    if not (root / "brain.toml").is_file():
        return []
    text = (root / "brain.toml").read_text(encoding="utf-8")
    paths = {root}
    for rel in re.findall(r'repo_path\s*=\s*"([^"]*)"', text):
        paths.add(root / rel if rel != "." else root)
    for tier in re.findall(r'tier\s*=\s*"([^"]+)"', text):
        if not tier.startswith("_"):
            paths.add(root / tier)
    return sorted(p for p in paths if p.is_dir())


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", default=None, help="repo root (default: this script's repo)")
    ap.add_argument("--all", action="store_true", help="every repo registered in brain.toml")
    ap.add_argument("--check", action="store_true", help="report only; write nothing")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    here = Path(__file__).resolve().parent.parent
    if args.all:
        targets = brain_repos(here)
        if not targets:
            print("no brain.toml found above this script — cannot resolve --all")
            return 1
    else:
        targets = [Path(args.repo).resolve() if args.repo else here]

    rc = 0
    for t in targets:
        rc |= regenerate(t, check_only=args.check, quiet=args.quiet)
    return rc


if __name__ == "__main__":
    sys.exit(main())
