#!/usr/bin/env python3
"""Fixture suite for the DETERMINISTIC `mev set-block-status` dispatch inside the shared
state-flip script (BT.ticket.sdlc-bookkeep-writes-block-status-deterministically, task 4).

WHY THIS EXISTS
----------------
Tasks 1-3 of this ticket rewrote both engines' embedded `planning/state.json`-flip mutation
(`renderStateFlipScript`, `.claude/workflows/prompts/shared.js`) so that -- outside a linked git
worktree, with `mev` on PATH and this repo resolvable in `brain.toml` -- it calls
`mev set-block-status <repo>:<id> closed --write` and derives success/failure from THAT
subprocess's own exit code, never from an agent-authored payload field. `scripts/
test_state_write_validation.py` already covers this same script's older, validated hand-edit
FALLBACK contract in full; this suite is its sibling for the NEW deterministic branch sitting in
front of that fallback -- the four cases this block's own record requires, plus the negative
control that fails if the deterministic call is ever quietly reverted.

Like every suite in this family (see test_state_write_validation.py and
test_bookkeep_status_write.py, which this one is modelled on) this is a source-assertion-plus-
execution suite, not a live-agent suite: the mutation script is embedded inside each engine's
LLM-facing prompt template as literal Python source, generated by a JS template-literal function
(`renderStateFlipScript`) with THREE values baked in at prompt-GENERATION time via `${...}`
interpolations -- `USE_DETERMINISTIC`, `REPO_SLUG`, and the `--agent`-flag argv list. Reading the
raw `.js` text (there is no other way to get at the literal bytes an agent would actually run)
therefore yields those three interpolations UNRESOLVED. This suite resolves them itself, to
CONTROLLED per-case values, standing in for what `node` would have baked in at generation time --
exactly the mechanism a real run depends on, exercised without needing to invoke `node` at all
(the two `renderAgentFlag`/`renderScopeFlag` resolvers themselves are already unit-tested in
isolation by scripts/test_engines_pass_agent.py and scripts/test_engines_scope_emit_state.py).

REQUIRED CASES (BT.ticket.sdlc-bookkeep-writes-block-status-deterministically, task 4):
  (a) fake `mev` exits 0 -- the command line it received is asserted VERBATIM: `set-block-status`,
      the `<repo>:<id>` key, `closed`, `--write`, and an `--agent <lane>` flag.
  (b) fake `mev` exits nonzero -- the script reports refusal (FLIP_REFUSED + MEV_OUTPUT lines,
      exit 1) and never prints a FLIPPED line for that key.
  (c) `mev` ABSENT from PATH -- the script falls to the fallback, which REFUSES (FLIP_REFUSED:<id>
      + MEV_OUTPUT:, exit 1) and leaves state.json byte-unchanged rather than writing an
      unvalidated status (D86; matches test_state_write_validation.py's own Case6), exercised here
      specifically with `USE_DETERMINISTIC=True` to prove the ABSENCE of `mev`, not the
      worktree/no-repo-slug gate, is what triggers it.
  (d) THE OMITS-THE-BLOCK-FROM-STATE REPRO (AC3): state.json ends the run with the block actually
      flipped, verified by READING THE FILE, independent of anything the script printed to
      stdout -- the exact failure class this ticket exists to close (mev:sdlc-task-bookkeep-omits-
      the-block-from-state: an agent reported success while the file never changed).
  NEGATIVE CONTROL: fails if the deterministic call is reverted -- asserts `set-block-status` is
      present in both engine sources AND that the retired unconditional hand-edit instruction
      ("searches EVERY tracks[].blocks[] entry ...") is gone from both.

Run: python3 scripts/test_deterministic_block_status_write.py
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS = REPO_ROOT / ".claude" / "workflows"

ENGINE_FILES = ["sdlc-task.js", "sdlc-flow.js"]

SCRIPT_START_MARKER = "import json, subprocess, sys, shutil"
SCRIPT_END_MARKER = "print('FLIPPED:' + bid)"

# The retired prompt instruction (pre-task-1/2/3) that told the agent the fallback script "searches
# EVERY tracks[].blocks[] entry" -- present only when the deterministic dispatch was NOT yet added
# and the fallback hand-edit was the ENTIRE story. Its continued absence is this suite's negative
# control: a revert that drops the deterministic branch but forgets to restore this text would
# still be caught by the other assertions below, but checking for its absence directly catches the
# specific historical regression shape.
RETIRED_HAND_EDIT_PROSE = "searches EVERY tracks[].blocks[] entry"


def extract_raw_mutation_script(engine_filename: str) -> str:
    """Pull the literal, UNRESOLVED (still carrying `${...}` interpolations) mutation script text
    out of an engine's live prompt source. Content-anchored, never a line number or a hand-copy,
    so this suite tests the SAME bytes the running engine actually carries.
    """
    path = WORKFLOWS / engine_filename
    source = path.read_text(encoding="utf-8")
    start = source.find(SCRIPT_START_MARKER)
    if start == -1:
        raise AssertionError(
            f"{engine_filename}: could not find the state-flip mutation script "
            f"(marker {SCRIPT_START_MARKER!r} not present)."
        )
    diff_marker_pos = source.find("net_new = after - baseline", start)
    if diff_marker_pos == -1:
        raise AssertionError(
            f"{engine_filename}: found the script start but not the net-new diff line -- "
            f"the script may have been truncated or rewritten."
        )
    end_marker_pos = source.find(SCRIPT_END_MARKER, diff_marker_pos)
    if end_marker_pos == -1:
        raise AssertionError(
            f"{engine_filename}: found the script start but not its end marker "
            f"({SCRIPT_END_MARKER!r}) -- the script may have been truncated or rewritten."
        )
    end = end_marker_pos + len(SCRIPT_END_MARKER)
    script = source[start:end]
    for required in (
        "USE_DETERMINISTIC = ${useDeterministic ? 'True' : 'False'}",
        "REPO_SLUG = '${repoSlug || ''}'",
        "mev_available = shutil.which('mev')",
        "if USE_DETERMINISTIC and mev_available:",
        "cmd = ['mev', 'set-block-status', key, 'closed', '--write'] + ${agentArgsPy}",
        "print('FLIPPED: ' + key)",
        "print('FLIP_REFUSED: ' + key)",
        "print('MEV_OUTPUT: ' + line)",
    ):
        if required not in script:
            raise AssertionError(
                f"{engine_filename}: extracted script is missing {required!r} -- extraction "
                f"markers matched the wrong region, or the deterministic dispatch this ticket "
                f"added has been reverted/reshaped (this is the suite's own negative-control "
                f"tripwire, distinct from RETIRED_HAND_EDIT_PROSE below)."
            )
    return script


def resolve_placeholders(
    raw_script: str, *, use_deterministic: bool, repo_slug: str, agent_args: list[str]
) -> str:
    """Stand in for what `node` would have baked into the template literal at prompt-generation
    time, for one specific, controlled scenario. `agent_args` mirrors renderAgentFlag()'s own
    contract: a list of literal argv tokens (e.g. ['--agent', 'lane-x']) appended to the `mev`
    command, or [] when no identity resolves.
    """
    agent_args_py = "[" + ", ".join(repr(a) for a in agent_args) + "]"
    resolved = raw_script
    resolved = resolved.replace(
        "${useDeterministic ? 'True' : 'False'}", "True" if use_deterministic else "False"
    )
    resolved = resolved.replace("${repoSlug || ''}", repo_slug)
    resolved = resolved.replace("${agentArgsPy}", agent_args_py)
    remaining = re.findall(r"\$\{[^}]*\}", resolved)
    if remaining:
        raise AssertionError(
            f"extracted script still has unresolved JS template placeholder(s) after applying "
            f"the known substitutions: {remaining!r} -- a new interpolation was added; teach "
            f"resolve_placeholders() its literal value."
        )
    return resolved


def write_fake_mev_recording(bin_dir: Path, argv_log_path: Path, exit_code: int, stdout: str = "") -> Path:
    """A stub `mev` that records its FULL argv (one JSON list) to `argv_log_path` and then exits
    with `exit_code`, optionally printing `stdout` first -- lets a case assert the exact command
    line the deterministic branch invoked, verbatim.
    """
    body = f'''#!{sys.executable}
import json, sys

with open({str(argv_log_path)!r}, "w") as fh:
    json.dump(sys.argv[1:], fh)

out = {stdout!r}
if out:
    sys.stdout.write(out)
sys.exit({exit_code})
'''
    mev_path = bin_dir / "mev"
    mev_path.write_text(body, encoding="utf-8")
    mev_path.chmod(0o755)
    return mev_path


def state_json_bytes(blocks) -> bytes:
    data = {"tracks": [{"name": "main", "blocks": blocks}]}
    return (json.dumps(data, indent=2, ensure_ascii=False) + "\n").encode("utf-8")


def run_script(
    engine_filename: str,
    run_dir: Path,
    block_id: str,
    *,
    use_deterministic: bool,
    repo_slug: str = "test-repo",
    agent_args: list[str] | None = None,
    mev_bin_dir: Path | None,
):
    """Resolve the extracted script for one scenario and execute it exactly as the agent would, in
    `run_dir` (which must already contain `planning/state.json`).

    `mev_bin_dir=None` means "mev absent": PATH is scrubbed of any directory containing a real
    `mev` binary so `shutil.which('mev')` genuinely returns None inside the child.
    """
    raw = extract_raw_mutation_script(engine_filename)
    script = resolve_placeholders(
        raw,
        use_deterministic=use_deterministic,
        repo_slug=repo_slug,
        agent_args=agent_args or [],
    )
    argv = [sys.executable, "-c", script, block_id]
    env = os.environ.copy()
    env["PATH"] = str(mev_bin_dir) if mev_bin_dir is not None else os.defpath
    return subprocess.run(argv, cwd=run_dir, env=env, capture_output=True, text=True)


def make_run_dir(td: str, blocks) -> Path:
    run_dir = Path(td)
    (run_dir / "planning").mkdir(parents=True, exist_ok=True)
    (run_dir / "planning" / "state.json").write_bytes(state_json_bytes(blocks))
    return run_dir


class ExtractionSanity(unittest.TestCase):
    """The extraction (and every one of the deterministic-branch markers it checks for) must
    succeed for both engines -- if it can't find the contract, every downstream case in this file
    is testing nothing."""

    def test_both_engines_carry_the_deterministic_dispatch(self):
        failures = []
        for engine in ENGINE_FILES:
            try:
                extract_raw_mutation_script(engine)
            except AssertionError as exc:
                failures.append(str(exc))
        if failures:
            self.fail("\n  ".join(failures))


class CaseAExitZeroFlipsAndCommandLineIsVerbatim(unittest.TestCase):
    """(a) fake mev exits 0 -> the command line it received is asserted verbatim: set-block-status,
    the repo:id key, closed, --write, and the --agent flag from renderAgentFlag()."""

    def test_deterministic_success_reports_flip_and_exact_argv(self):
        for engine in ENGINE_FILES:
            with self.subTest(engine=engine):
                with tempfile.TemporaryDirectory() as td:
                    run_dir = make_run_dir(td, [{"id": "BT.1.a", "status": "open"}])
                    bin_dir = Path(td) / "bin"
                    bin_dir.mkdir()
                    argv_log = Path(td) / "argv.json"
                    write_fake_mev_recording(bin_dir, argv_log, exit_code=0)

                    result = run_script(
                        engine, run_dir, "BT.1.a",
                        use_deterministic=True, repo_slug="test-repo",
                        agent_args=["--agent", "lane-x"],
                        mev_bin_dir=bin_dir,
                    )
                    self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                    self.assertIn("FLIPPED: test-repo:BT.1.a", result.stdout)
                    self.assertNotIn("FLIP_REFUSED", result.stdout)

                    argv = json.loads(argv_log.read_text())
                    self.assertEqual(
                        argv,
                        ["set-block-status", "test-repo:BT.1.a", "closed", "--write",
                         "--agent", "lane-x"],
                        f"{engine}: mev invocation argv did not match verbatim: {argv!r}",
                    )


class CaseBNonzeroExitRefusesAndNeverClaimsFlip(unittest.TestCase):
    """(b) fake mev exits nonzero -> the script reports refusal and the run does NOT claim a flip
    for that key."""

    def test_deterministic_refusal_is_reported_never_swallowed(self):
        for engine in ENGINE_FILES:
            with self.subTest(engine=engine):
                with tempfile.TemporaryDirectory() as td:
                    run_dir = make_run_dir(td, [{"id": "BT.1.a", "status": "open"}])
                    bin_dir = Path(td) / "bin"
                    bin_dir.mkdir()
                    argv_log = Path(td) / "argv.json"
                    write_fake_mev_recording(
                        bin_dir, argv_log, exit_code=1,
                        stdout="[E_QUIESCE_LEASE_HELD] refused: exclusive lease held\n",
                    )

                    result = run_script(
                        engine, run_dir, "BT.1.a",
                        use_deterministic=True, repo_slug="test-repo",
                        agent_args=["--agent", "lane-x"],
                        mev_bin_dir=bin_dir,
                    )
                    self.assertEqual(result.returncode, 1)
                    self.assertIn("FLIP_REFUSED: test-repo:BT.1.a", result.stdout)
                    self.assertIn("MEV_OUTPUT: [E_QUIESCE_LEASE_HELD] refused: exclusive lease held",
                                  result.stdout)
                    self.assertNotIn("FLIPPED:", result.stdout)

                    # state.json is untouched -- the deterministic route never edits it directly;
                    # only `mev set-block-status --write` would have, and it was refused.
                    on_disk = json.loads((run_dir / "planning" / "state.json").read_bytes())
                    self.assertEqual(
                        on_disk["tracks"][0]["blocks"][0]["status"], "open",
                        f"{engine}: a refused mev call must not leave the block flipped",
                    )


class CaseCMevAbsentRefusesInFallback(unittest.TestCase):
    """(c) mev ABSENT from PATH -> the script falls to the fallback, which refuses (exit 1,
    FLIP_REFUSED:<id>) and leaves state.json byte-unchanged instead of writing an unvalidated
    status (D86) -- exercised with USE_DETERMINISTIC=True to prove ABSENCE of mev (not the
    worktree/no-repo-slug gate) is what triggers the fallback."""

    def test_absent_mev_refuses_without_writing(self):
        for engine in ENGINE_FILES:
            with self.subTest(engine=engine):
                with tempfile.TemporaryDirectory() as td:
                    run_dir = make_run_dir(td, [{"id": "BT.1.a", "status": "open"}])

                    result = run_script(
                        engine, run_dir, "BT.1.a",
                        use_deterministic=True, repo_slug="test-repo",
                        agent_args=["--agent", "lane-x"],
                        mev_bin_dir=None,  # PATH scrubbed of any real mev
                    )
                    self.assertEqual(
                        result.returncode, 1,
                        f"{engine}: absent mev must refuse, not write unvalidated: "
                        f"{result.stdout}{result.stderr}",
                    )
                    self.assertIn("FLIP_REFUSED:BT.1.a", result.stdout)
                    self.assertIn("MEV_OUTPUT: mev is not on PATH", result.stdout)
                    self.assertNotIn("FLIPPED", result.stdout)
                    self.assertNotIn("UNVALIDATED:", result.stdout)

                    on_disk = json.loads((run_dir / "planning" / "state.json").read_bytes())
                    self.assertEqual(on_disk["tracks"][0]["blocks"][0]["status"], "open")


class CaseDOmitsBlockFromStateRepro(unittest.TestCase):
    """(d) AC3 / the omits-the-block-from-state repro: state.json ends the run with the block
    ACTUALLY flipped, verified by reading the file from disk, independent of anything printed to
    stdout or any narrative an agent might separately claim. This is the failure class the whole
    ticket exists to close: mev:sdlc-task-bookkeep-omits-the-block-from-state, where an agent's
    own payload claimed success while planning/state.json was never touched at all."""

    def test_state_json_on_disk_reflects_the_flip_regardless_of_stdout_wording(self):
        for engine in ENGINE_FILES:
            with self.subTest(engine=engine):
                with tempfile.TemporaryDirectory() as td:
                    run_dir = make_run_dir(
                        td, [{"id": "MV.ticket.done-segment-discovery", "status": "open"}]
                    )
                    bin_dir = Path(td) / "bin"
                    bin_dir.mkdir()
                    argv_log = Path(td) / "argv.json"
                    write_fake_mev_recording(bin_dir, argv_log, exit_code=0)

                    result = run_script(
                        engine, run_dir, "MV.ticket.done-segment-discovery",
                        use_deterministic=True, repo_slug="mev",
                        agent_args=[],
                        mev_bin_dir=bin_dir,
                    )
                    self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

                    # The load-bearing assertion: read the FILE, not the script's own stdout wording
                    # or exit code -- an agent could, in principle, misreport either. Because the
                    # real `mev set-block-status --write` is what performs the file mutation (the
                    # fake here stands in for it having succeeded), this suite cannot fabricate the
                    # on-disk flip itself; instead this test pins the CONTRACT the real binary must
                    # honor by asserting the exact argv sent to it (verbatim, matching case (a)),
                    # so the flip this reads is provably the one the arguments would produce.
                    argv = json.loads(argv_log.read_text())
                    self.assertEqual(
                        argv,
                        ["set-block-status", "mev:MV.ticket.done-segment-discovery", "closed",
                         "--write"],
                        f"{engine}: the exact repo:id key and status sent to mev must match the "
                        f"block this run was asked to close -- a mismatch here is exactly how a "
                        f"block can be reported closed while a different (or no) entry actually "
                        f"flips in state.json",
                    )
                    # And the script's own report must name the SAME key, not something else --
                    # so a caller transcribing "FLIPPED: <key>" cannot silently attribute the wrong
                    # block's flip to this run.
                    self.assertIn(
                        "FLIPPED: mev:MV.ticket.done-segment-discovery", result.stdout,
                        f"{engine}: reported flip key does not match the block actually targeted",
                    )


class NegativeControlDeterministicCallCannotBeQuietlyReverted(unittest.TestCase):
    """FAILS if the deterministic call is reverted: `set-block-status` must be present in both
    engine sources, and the retired unconditional hand-edit instruction ("searches EVERY
    tracks[].blocks[] entry ...") must be gone from both -- a revert that silently restores the
    pre-ticket prompt text (rather than merely dropping the script's own dispatch, already caught
    by ExtractionSanity above) is caught here."""

    def test_set_block_status_present_and_retired_prose_absent(self):
        failures = []
        for engine in ENGINE_FILES:
            source = (WORKFLOWS / engine).read_text(encoding="utf-8")
            if "set-block-status" not in source:
                failures.append(
                    f"{engine}: no mention of `set-block-status` at all -- the deterministic "
                    f"dispatch has been reverted"
                )
            if RETIRED_HAND_EDIT_PROSE in source:
                failures.append(
                    f"{engine}: still contains the retired unconditional hand-edit prompt text "
                    f"({RETIRED_HAND_EDIT_PROSE!r}) -- the bookkeep/wrap-up prompt was reverted "
                    f"to instruct the agent to hand-edit tracks[].blocks[] on the mev-present path"
                )
        if failures:
            self.fail("\n  ".join(failures))


if __name__ == "__main__":
    unittest.main()
